<?php
// $Id: creativecommons.module,v 1.9.2.26 2009/07/14 23:51:33 balleyne Exp $

/**
 * @file
 * Creative Commons Drupal module
 *   Allows content within a site or attached to a node to
 *   be assigned a Creative Commons license.
 *   http://creativecommons.org/license/
 *
 *
 * By: Peter Bull <pbull@ltc.org>
 * 2005-02-28 / digitalbicycle.org / ltc.org
 * This software is released under the terms of the LGPL license, relicensed
 * under GPLv2 for drupal.org.
 *
 * Utilizes code and inspiration from http://cclicense.sourceforge.net/
 *   Originally released by Blake Watters <sbw@ibiblio.org>
 *   under the terms of the LGPL license (now, GPLv2 for drupal.org).
 *
 */

//TODO: review support for metadata fields (is some of this redundant in Drupal?)
//TODO: move cc_settings_validate warning to somewhere else... needed for license selection form as well?
//TODO: hook_perm for setting licenses, not just admin

define('CC_PATH', drupal_get_path('module', 'creativecommons'));
define('CC_IMG_PATH', base_path() . CC_PATH .'/images/');
define('CC_JS_PATH', base_path() . CC_PATH .'/js/');
define('CC_API_ROOT', 'http://api.creativecommons.org/rest/1.5');

require_once('creativecommons.class.php');


/**
 * Enclose each arg in paragraph tags.
 */
//TODO: is there a drupal function that can replace this?
function cc_para() {
  $args = func_get_args();
  $p = '';
  foreach ($args as $c)
    $p .= "<p>$c</p>";
  return $p;
}


/**
 * Implementation of hook_perm().
 */
function creativecommons_perm() {
  return array('administer creative commons');
}


/**
 * Implementation of hook_menu().
 */
function creativecommons_menu() {
  $items = array();

  $items['admin/settings/creativecommons'] = array(
    'title' => 'Creative Commons',
    'description' => 'Configure the Creative Commons settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' =>  array('creativecommons_settings'),
    'access arguments' => array('administer creative commons')
  );

  $items['admin/settings/creativecommons/edit'] = array(
    'title' => 'settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10
  );

  $items['admin/settings/creativecommons/default'] = array(
    'title' => 'site defaults',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('creativecommons_site_defaults'),
    'access arguments' => array('administer creative commons'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/settings/creativecommons/types'] = array(
    'title' => 'content types',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('creativecommons_types_form'),
    'access arguments' => array('administer creative commons'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10
  );

  return $items;
}


/**
 * Implementation of hook_help().
 */
function creativecommons_help($path, $arg) {
  $cc_desc = 'A Creative Commons license helps you publish your work online while letting others know exactly what they can and can\'t do with your work. Creative Commons offers a flexible range of protections and freedoms for authors and artists, built upon the "all rights reserved" concept of traditional copyright to create a voluntary "some rights reserved" copyright.';
  $cc_desc_short = 'Assign a Creative Commons license to content that appears on the site.';
  $cc_node = 'Attaching a Creative Commons license to a node within Drupal can designate the content of that node, as well as any attached files, as available under that license.';
  $cc_url = 'For more information, visit <a href="http://creativecommons.org/learnmore">http://creativecommons.org/learnmore</a>.';

  switch ($path) {
    case 'admin/modules#description':
      return t($cc_desc_short);
    case 'admin/settings/creativecommons':
      return t(cc_para($cc_desc, $cc_node, $cc_url));
    case 'admin/help#creativecommons':
      return t(cc_para($cc_desc, $cc_node, $cc_url));
  }
}

/**
 * General Creative Commons settings page.
 */
function creativecommons_settings() {
  $available_license_types = creativecommons_get_available_license_types();
  $license_array_keys = creativecommons_get_licenses(array('jurisdiction' => variable_get('creativecommons_default_jurisdiction', '')), TRUE);
  $metadata_types_keys = creativecommons_get_metadata_types();

  $form['creativecommons_license'] = array(
    '#type' => 'fieldset',
    '#title' => t('License selection'),
  );

  $form['creativecommons_license']['creativecommons_available_license_types'] = array(
    '#type' => 'select',
    '#title' => t('Available license types'),
    '#default_value' => $available_license_types,
    '#options' => $license_array_keys,
    '#description' => t('Select the license types to make available to users.'),
    '#multiple' => TRUE,
  );

  //TODO: change to 'required_metadata' to be more clear
  $form['creativecommons_license']['creativecommons_required'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Required metadata fields'),
    '#default_value' => variable_get('creativecommons_required', array()),
    '#options' => $metadata_types_keys,
    '#description' => t('This option allows you to require specific metadata to be included when a license is applied.'),
  );

  //-------------------

  $form['creativecommons_display'] = array(
    '#type' => 'fieldset',
    '#title' => t('Node display'),
  );


  //TODO: reimplement
  /* $form['creativecommons_display']['creativecommons_display'] = array(
    '#type' => 'radios',
    '#title' => t('Display license information'),
    '#default_value' => variable_get('creativecommons_display', 1),
    '#options' => array(
      t('Display text'),
      t('Display text and Creative Commons logo'),
      t('Display text and icons'),
      t('Do not display license')
    ),
    '#description' => t('You can display license details when viewing a node.'),
    '#required' => TRUE,
    '#attributes' => FALSE,
  );*/

  $form['creativecommons_display']['creativecommons_rdf'] = array(
    '#type' => 'checkbox',
    '#title' => t('Insert RDF into HTML'),
    '#return_value' => 1,
    '#default_value' => variable_get('creativecommons_rdf', TRUE),
    '#description' => t('Attach machine-readable license information within the HTML to let visitors know what license applies to your works.'),
  );
  return system_settings_form($form);

}

/**
 * Validate general creative commons settings.
 */
function creativecommons_settings_validate($form, &$form_state) {
//TODO: should this be here? (no errors displays when settings page first loaded, and it sets message, not error)
  if (empty($form_state['values']['creativecommons_available_license_types']))
    drupal_set_message('No licenses are enabled.', 'warning');
}

/**
 * Creative Commons site license settings form
 */
function creativecommons_site_defaults() {
  global $base_url;
  $prefix = 'creativecommons_default';

  // Load default license
  $cc = creativecommons_get_default_license();

  // Check to see if default license is still available
  if (!$cc->is_available()) {
    $message = $cc->get_full_license_name();
    $message .= $cc->is_valid() ? ' is no longer available' : ' is not valid';
    drupal_set_message($message, 'warning');
  }

  $node->cc = $cc;

  $form['creativecommons_default_license'] = array(
    '#type' => 'fieldset',
    '#title' => t('Default license'),
  );

  $available_license_types = creativecommons_get_available_licenses(NULL, TRUE);

  // If None isn't an option, create blank first entry
  if (!in_array('', $available_license_types)) {
    $available_license_types = array_merge( array('' => ''), $available_license_types );
  }

  $form['creativecommons_default_license']['creativecommons_default_license_type'] = array(
    '#type' => 'select',
    '#title' => t('License type'),
    '#default_value' => variable_get('creativecommons_default_license_type', ''),
    '#options' => $available_license_types,
    '#description' => t('Select the site wide default license type for new content.'),
  );

  $q = creativecommons_get_questions_array('standard');
  $form['creativecommons_default_license']['creativecommons_default_jurisdiction'] = array(
    '#type' => 'select',
    '#title' => t('Default jurisdiction'),
    '#description' => t($q['jurisdiction']['description']),
    '#options' => creativecommons_format_jurisdiction_array($q['jurisdiction']['answers']),
    '#default_value' => variable_get('creativecommons_default_jurisdiction', ''),
  );


  // TODO: review
  /* append metadata fields and defaults site values
  global $base_url;
  $defaults = array('format' => 'interactive', 'source' => $base_url);
  foreach (array('description' => 'site_slogan', 'description' => 'site_mission',
    'title' => 'site_name') as $mn => $vv) {
    $gv = variable_get($vv, NULL);
    if (!is_null($gv) && drupal_strlen($gv) > 0)
      $defaults[$mn] = $gv;
  }

  if (!is_null($node->cc->license_type) && $node->cc->license_type != 'none') {
    $display2 = creativecommons_build_metadata_fields($node, $prefix, $defaults);
    $form['select_license_form']['creativecommons_site']['metadata'] = $display2['creativecommons_site']['metadata'];
  }
   end review */


  // site license display
  $form['creativecommons_site_license'] = array(
    '#type' => 'fieldset',
    '#title' => t('Site license'),
  );
  $form['creativecommons_site_license']['creativecommons_site_license_display'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use default license as site wide license to be displayed on every page?'),
    '#return_value' => 1,
    '#default_value' => variable_get('creativecommons_site_license_display', FALSE),
  );
  $form['creativecommons_site_license']['creativecommons_site_license_additional_text'] = array(
    '#type' => 'textarea',
    '#title' => t('Additional text'),
    '#default_value' => variable_get('creativecommons_site_license_additional_text', NULL),
    '#cols' => 60,
    '#rows' => 3,
    '#description' => t('This text will accompany the display of the site license.'),
    '#attributes' => NULL,
    '#required' => NULL,
  );

  $form['#submit'][] = 'creativecommons_site_defaults_submit';

  return system_settings_form($form);
}

/**
 * Validate default site license uri
 */
function creativecommons_site_defaults_validate($form, &$form_state) {
  $license_type = $form_state['values']['creativecommons_default_license_type'];
  $jurisdiction = $form_state['values']['creativecommons_default_jurisdiction'];

  $license_uri = creativecommons_get_license_uri_from_available($license_type, $jurisdiction);
  $form_state['values']['creativecommons_default_license_uri'] = $license_uri;

  if ($license_uri) {
    creativecommons_validate_license_uri('creativecommons_default_license_type', $license_uri);
  }
}

/**
 * Form builder. Allow administrator to enable Creative Commons licensing for
 * content types in one central location.
 */
function creativecommons_types_form() {
  $form = array();

  $form['help'] = array(
    '#type' => 'item',
    '#value' => t('Enable Creative Commons licensing for the following content types.'),
  );

  foreach (node_get_types('names') as $type => $name) {
    $form['creativecommons_type_'. $type] = array(
      '#type' => 'checkbox',
      '#title' => $name,
      '#return_value' => 1,
      '#default_value' => creativecommons_node_type_is_enabled($type),
    );
  }

  return system_settings_form($form);
}


/**
 * Display license selection form
 *
 * @param $simple - use simple chooser if true
 */
function creativecommons_select_license_form($node, $key, $form_state_segment = NULL) {
  // load available licenses
  $jurisdiction = variable_get('creativecommons_default_jurisdiction', '');
  $available_licenses = creativecommons_get_available_licenses( array('jurisdiction' => $jurisdiction) );

  // If license uri selected in form, use that
  if ($form_state_segment && isset($form_state_segment[$key])) {
    $selected_license_uri = $form_state_segment[$key];
  }
  // Otherwise, use license uri attached to node
  elseif ($node->cc) {
    $selected_license_uri = $node->cc->license_uri;
  }
  // Otherwise, use default uri
  else {
    $selected_license_uri = creativecommons_get_default_license_uri();
  }

  // TODO: make this more efficient
  // Double-check URI to make sure it matches up with correct license type for this jurisdiction
  $old_selected_license_uri = $selected_license_uri;
  $license_type = creativecommons_get_license_type_from_uri($selected_license_uri);
  $selected_license_uri = creativecommons_get_license_uri_from_available($license_type, $jurisdiction);

  // Warn user if changed
  if ($selected_license_uri != $old_selected_license_uri) {
    //TODO: improve message: three cases (version change, jurisdiction change, availability change)
    //TODO: this doesn't work for None selections
    drupal_set_message('Your license selection has been automatically altered. Please review.', 'warning');
    /**
      * Cases...
      * 1) jurisdiction changed
      * 2) version changed
      * 3) license was made unavailable
      */
  }


  /**
    * If selected_license_uri is blank but None is not an available type,
    * then a blank entry is placed at the beginning of the list and the field
    * is set to 'required'. This forces the user to actively select a license,
    * rather than just defaulting to the first on the list.
    *
    * This will only arise in the following cases:
    *  - if content had no license (None), but that is no longer an available type
    *  - if there is no site default set, but None is not an available type
    */
  $required = FALSE;
  if (!$selected_license_uri && !in_array('', $available_licenses)) {
    $required = TRUE;
    $available_licenses = array_merge( array('' => ''), $available_licenses);
  }


  // Form element
  $form['select_license_form'][$key] = array(
    '#type' => 'select',
    '#title' => t('Creative Commons License'),
    '#default_value' => $selected_license_uri,
    '#options' => $available_licenses,
    '#attributes' => $extra,
    '#description' => NULL,
    '#required' => $required,
  );


  return $form;
}

/**
 * Provides license uri validation for form validate methods to use.
 */
function creativecommons_validate_license_uri($license_uri_key, $license_uri) {
  // Check to see if selected license is available
  $cc = new creativecommons_license($license_uri);
  if (!$cc->is_available()) {
    $message = $cc->get_full_license_name();
    $message .= $cc->is_valid() ? ' is no longer available.' : ' is not a valid license.';

    form_set_error($license_uri_key, $message);
  }
}



/**
 * Return default license. 'Empty' license returned if no default set.
 */
function creativecommons_get_default_license() {
  $license_uri = creativecommons_get_default_license_uri();
  return new creativecommons_license($license_uri);
}

/**
 * Return default license URI.
 */
function creativecommons_get_default_license_uri() {
  return variable_get('creativecommons_default_license_uri', '');
}

/**
 * Parse license URI and return type.
 * @param $uri - a valid CC license uri
 * @return license type (e.g. 'by-sa')
 */
function creativecommons_get_license_type_from_uri($uri) {
  $parts = explode('/', $uri);

  return $parts[4];
}

/**
 * Strip out jurisdiction and version from license name.
 *
 * @param $name - full name of a CC license
 * @return license name, without version number or jurisdiction
 */
function creativecommons_generic_license_name($full_name) {
  $name_parts = explode(' ', $full_name);
  $version_part = count($name_parts);

  // Find the version number (only numeric part)
  $i = 0;
  foreach ($name_parts as $part) {
    if (is_numeric($part))
      $version_part = $i;
    $i++;
  }

  // Build the name, up to but not including version number
  $name = $name_parts[0];
  for ($i=1;$i<$version_part;$i++)
    $name .= ' '. $name_parts[$i] ;

  return $name;
}


//TODO: this method is not in use -- questions seem more reliable
function creativecommons_get_jurisdictions() {
  $uri = '/support/jurisdictions';
  $xml = '<jurisdictions>'. creativecommons_return_xml($uri) .'</jurisdictions>';

  $parser = xml_parser_create();
  xml_parser_set_option($parser, XML_OPTION_SKIP_WHITE, 1);
  xml_parser_set_option($parser, XML_OPTION_CASE_FOLDING, 0);
  xml_parse_into_struct($parser, $xml, $values, $index);
  xml_parser_free($parser);

  $jurisdictions = array('' => 'Generic');
  foreach ($values as $key) {
    if ($key['tag'] == 'option' && $key['level'] == 2) {
      $id = explode('/', $key['attributes']['value']);
      $jurisdictions[$id[4]] = $key['value'];
    }
  }

  return $jurisdictions;
}

/**
 * Take the raw array of jurisdictions from the CC API and format it for use in
 * a Drupal form by flipping keys/values, and sorting by Jurisdiction name
 * @param $raw_array - array of jurisdictions from CC API
 * @return array of jurisdictions for use in Drupal form
 */
function creativecommons_format_jurisdiction_array($raw_array) {
  $jurisdictions = array();

  foreach ($raw_array as $name => $id)
    $jurisdictions[$id] = $name;

  // Sort by Jurisdiction name
  asort($jurisdictions);

  // Move special case 'Generic' to front
  $generic = array('' => $jurisdictions['']);
  unset($jurisdictions['']);
  $jurisdictions = array_merge($generic, $jurisdictions);

  return $jurisdictions;
}


/**
 * Return array of all available licenses, grouped by class, for use in a Drupal
 * form.
 *
 * @param $options - optional array of options for CC API simple license
 * chooser, as per: http://api.creativecommons.org/docs/readme_15.html#simple-chooser
 * @param $value_as_type - if set to TRUE, the key for each license will be the
 *                        license type (e.g. 'by-sa'), instead of the full URI.
 * @return array of all available license
 */
function creativecommons_get_licenses($options = NULL, $value_as_type = FALSE) {
  $licenses = array();

  // Unlicensed
  $licenses[''] = 'None (All Rights Reserved)';

  // License classes
  $licenses['Creative Commons'] = array();
  $licenses['Public Domain'] = array();

  // Manual adjustments for 'standard' class
  $parser = xml_parser_create();
  xml_parser_set_option($parser, XML_OPTION_SKIP_WHITE, 1);
  xml_parser_set_option($parser, XML_OPTION_CASE_FOLDING, 0);

  $uri = '/simple/chooser';
  if ($options)
    $uri .= '?'. http_build_query($options);
  $standard_xml = '<standard>'. creativecommons_return_xml($uri) .'</standard>';

  xml_parse_into_struct($parser, $standard_xml, $standard_licenses, $index);
  xml_parser_free($parser);

  foreach ($standard_licenses as $key) {
    if ($key['tag'] == 'option' && $key['level'] == 2) {
      // strip out license type identifier from uri
      $license_uri = $key['attributes']['value'];
      $license_type = creativecommons_get_license_type_from_uri($license_uri);

      $license_key = $value_as_type ? $license_type : $license_uri;
      $license_name = $value_as_type ? creativecommons_generic_license_name($key['value']) : $key['value'];

      $license_class = $license_type == 'publicdomain' ? 'Public Domain' : 'Creative Commons';
      $licenses[$license_class][$license_key] = $license_name;
    }
  }

  //Add CC0
  //TODO: http://creativecommons.org/license/zero/partner?lang=en&partner={partner}&exit_url={exit_url}&license_code=publicdomain&stylesheet={stylesheet}
  $zero_uri = 'http://creativecommons.org/publicdomain/zero/1.0/';
  $zero_title = 'CC0 1.0 Universal';

  if ($value_as_type)
    $licenses['Public Domain']['zero'] = creativecommons_generic_license_name($zero_title);
  else
    $licenses['Public Domain'][$zero_uri] = $zero_title;

  return $licenses;
}


/**
 * Return an array of available license types.
 */
function creativecommons_get_available_license_types() {
  return variable_get('creativecommons_available_license_types', array());
}

/**
 * Return an array of available licenses.
 * @param $options -- options for querying the CC API for available licenses
 * @param $first_entry_blank -- if TRUE, insert blank entry at start of array
 *
 * @return array of available licenses
 */
function creativecommons_get_available_licenses($options = NULL, $value_as_type = FALSE) {
  $licenses = creativecommons_get_licenses($options, $value_as_type);

  $available_licenses = creativecommons_remove_unavailable_licenses($licenses);

  // Clear out empty license classes (e.g. Don't show Public Domain optgroup if PD and CC0 not enabled)
  foreach ($available_licenses as $class => $value) {
    if (empty($value)) {
      unset($available_licenses[$class]);
    }
  }

  return $available_licenses;
}

/**
 * Takes a list of licenses and unsets any which are not available in the site settings.
 * @param $list  list of licenses to check
 */
function creativecommons_remove_unavailable_licenses($list, $available_license_types = NULL) {

  if (!$available_license_types)
    $available_license_types = creativecommons_get_available_license_types();

  foreach ($list as $key => $value) {
    if (is_array($value)) {
      $list[$key] = creativecommons_remove_unavailable_licenses(&$value, $available_license_types);
    }
    elseif (!in_array($key, $available_license_types) && !in_array(creativecommons_get_license_type_from_uri($key), $available_license_types))
      unset($list[$key]);
  }

  return $list;
}

/**
 * Return true if license uri receives a valid response from CC API, false
 * otherwise.
 */
function creativecommons_is_available_license_uri($license_uri) {
  $cc = new creativecommons_license($license_uri);
  return $cc->is_available();
}

/**
 * Lookup license uri based on type and jurisdiction (only searches available types)
 * @param $license_type (e.g. by, by-sa)
 * @param $jurisdiction (e.g. us, ca)
 * @return valid license-uri, or empty string if none found
 */
function creativecommons_get_license_uri_from_available($license_type, $jurisdiction) {
  // TODO: option to search all licenses?
  $available_licenses = creativecommons_get_available_licenses( array('jurisdiction' => $jurisdiction) );

  foreach ($available_licenses as $class => $licenses) {
    if (is_array($licenses)) {
      foreach ($licenses as $uri => $title) {
        if ($license_type == creativecommons_get_license_type_from_uri($uri)) {
          $license_uri = $uri;
        }
      }
    }
  }

  return $license_uri;
}

/**
 * Send HTTP Request to CC API services.
 * $uri     relative uri of file content on CC api site, not inclucing interface root (can be '')
 * $headers An array containing an HTTP header => value pair.
 * $method  A string defining the HTTP request to use.
 * $data    A string containing data to include in the request.
 */
function creativecommons_api_request($uri, $headers = array(), $method = 'GET', $data = NULL) {

  $uri = CC_API_ROOT . (strpos($uri, '/') === 0 ? $uri : '/'. $uri);

  $result = drupal_http_request($uri, $headers, $method, $data);

  if ($result->error)
    drupal_set_message('Error accessing CC API: '. $result->error, 'error', FALSE);

  return $result;
}

/**
 * Refreshes cached XML if file is greater than $hrs hours old
 * $filename	name up file to be retrieved/updated
 * $uri		uri of file content on CC api site, beyond the interface root (if any)
 * $hrs		file should be updated if older then X number of hours
 * $update	force update of the file
 */
function creativecommons_return_xml($uri, $hrs = 24, $update = FALSE) {
  // check for xml variable
  $xml = variable_get('creativecommons_api_'. $uri, NULL);
  if ($xml) {

    // get timestamp ***directly from variables table*** to avoid caching
    $result = db_query("SELECT value FROM {variable} WHERE name = '%s'", 'creativecommons_api_'. $uri .'_timestamp');
    if ($row = db_fetch_object($result)) {
      if ($ts = unserialize($row->value)) {
        $diff = (time() - $ts)/60/60;
        if ($diff >= $hrs)
          $update = TRUE;
      }
      else $update = TRUE;
    }
    else $update = TRUE;
  }
  else $update = TRUE;

  // request xml
  if ($update) {
    $headers = array();
    $result = creativecommons_api_request($uri, $headers);
    switch ($result->code) {
      case 200:
        variable_set('creativecommons_api_'. $uri, $result->data);
        variable_set('creativecommons_api_'. $uri .'_timestamp', time());
        return $result->data;
        break;
      default:
        return;
        break;
    }
  }
  else return $xml;
}

/**
 * Return associative array of metadata names/descriptions
 */
function creativecommons_get_metadata_types() {
  return array(
    'format' => t('Format of work'),
    'title' => t('Title of work'),
    'description' => t('Description'),
    'creator' => t('Creator\'s name'),
    'rights' => t('<a href="http://creativecommons.org/jargon/copyright" onclick="cc_popup(\'http://creativecommons.org/jargon/copyright\');return FALSE;">Copyright</a> holder\'s name'),
    'date' => t('<a href="http://creativecommons.org/jargon/copyright_date" onclick="cc_popup(\'http://creativecommons.org/jargon/copyright_date\');return FALSE;">Year of copyright</a>'),
    'source' => t('<a href="http://creativecommons.org/jargon/source_work" onclick="cc_popup(\'http://creativecommons.org/jargon/source_work\');return FALSE;">Source work</a> URL')
  );
}


/**
 * Return array of questions for specified license
 */
function creativecommons_get_questions_array($license_id) {
  $question_xml = creativecommons_get_questions_xml($license_id);
  $parser = xml_parser_create();
  xml_parser_set_option($parser, XML_OPTION_SKIP_WHITE, 1);
  xml_parser_set_option($parser, XML_OPTION_CASE_FOLDING, 0);
  xml_parse_into_struct($parser, $question_xml, $values, $index);
  xml_parser_free($parser);

  $questions = array();
  foreach ($values as $xn) {

    // new question array item
    if ($xn['tag'] == 'field' && $xn['type'] == 'open') {
      $current = $xn['attributes']['id'];
      $questions[$current] = array();
    }

    // set description
    if ($xn['tag'] == 'description')
      $questions[$current]['description'] = $xn['value'];

    // set question
    if ($xn['tag'] == 'label' && is_null($questions[$current]['answers'])
      && $current !== NULL && is_null($ans_lbl)) {
      $questions[$current]['question'] = $xn['value'];
    }

    // set answer labels/values
    if ($ans_lbl !== NULL && $ans_val !== NULL) {
      $questions[$current]['answers'][$ans_val] = $ans_lbl;
      $ans_lbl = NULL;
      $ans_val = NULL;
    }
    if ($xn['tag'] == 'enum' && $xn['type'] == 'open')
      $ans_lbl = $xn['attributes']['id'];
    if ($xn['tag'] == 'label' && $ans_lbl !== NULL)
      $ans_val = $xn['value'];
  }

  return $questions;
}

/**
 * Return xml defining questions/answers for a specific creative commons license
 */
function creativecommons_get_questions_xml($license_id) {
  if ($license_id != 'none' && !is_null($license_id)) {
    $filename = $license_id .'.xml';
    return creativecommons_return_xml('/license/'. $license_id .'/');
  }
  return;
}

/**
 * Loop thru metadata and build form fields
 */
function creativecommons_build_metadata_fields($node, $prefix, $defaults = NULL) {
  // loop thru metadata fields
  $fields = '';
  $metadata_types = creativecommons_get_metadata_types();
  foreach ($metadata_types as $m => $d) {
    $sel = ($node->cc->metadata[$m]) ? $node->cc->metadata[$m] : '';
    if (is_array($defaults) && array_key_exists($m, $defaults)) {
      if (is_null($sel))
        $sel = $defaults[$m];
    }

    // build metadata form fields
    switch (drupal_strtolower($m)) {
      case 'format':
        $formats = creativecommons_get_formats();
        $form[$prefix]['metadata'][$m] = array(
          '#type' => 'select',
          '#title' => t($d),
          '#default_value' => $sel,
          '#options' => $formats,
          '#description' => NULL,
          '#attributes' => NULL,
          '#required' => $req,
        );
        break;

      case 'description':
        $form[$prefix]['metadata'][$m] = array(
          '#type' => 'textarea',
          '#title' => t($d),
          '#default_value' => $sel,
          '#cols' => 60,
          '#rows' => 5,
          '#description' => NULL,
          '#attributes' => NULL,
          '#required' => $req,
        );
        break;

      default:
        $form[$prefix]['metadata'][$m] = array(
          '#type' => 'textfield',
          '#title' => t($d),
          '#default_value' => $sel,
          '#size' => 50,
          '#maxlength' => 255,
          '#description' => NULL,
          '#attributes' => NULL,
          '#required' => $req,
        );
        break;
    }
  }
return system_settings_form($form);
}


/**
 * Return array of formats.
 * Uses associative array to preserve content name in form values.
 */
function creativecommons_get_formats() {
  $f = array(
    'other' => 'Other',
    'audio' => 'Audio',
    'video' => 'Video',
    'image' => 'Image',
    'text' => 'Text',
    'interactive' => 'Interactive');
  return $f;
}


/**
 * Implementation of hook_nodeapi().
 */
function creativecommons_nodeapi(&$node, $op, $arg, $a4) {

  switch ($op) {
    // settings   'form post replaced by form_api
    case 'load':
      if (creativecommons_node_type_is_enabled($node->type))
        $node->cc = creativecommons_load($node);
      break;

    case 'view':
      creativecommons_view($node, FALSE, FALSE, TRUE);
      break;

    case 'insert':
    case 'update':
          //TODO: create update query somewhere instead of always deleting
          creativecommons_delete($node);
          creativecommons_save($node);
      break;

    case 'delete':
      creativecommons_delete($node);
      break;

    //TODO: review
    case 'rss item':
      if ($item_license = creativecommons_xml($node))
        return $item_license;
      break;

  }
  return $output;
}

/**
 * Implementation of hook_form_alter().
 */
function creativecommons_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'node_type_form' && isset($form['identity']['type'])) {
    $node->type = $form['#node_type']->type;
    $form['workflow']['creativecommons'] = array(
      '#type' => 'checkbox',
      '#title' => t('Allow user to attach a Creative Commons license'),
      '#description' => t('User will be able to select a license while editing content.'),
      '#return_value' => 1,
      '#default_value' => creativecommons_node_type_is_enabled($node->type),
    );
  }
  elseif (isset($form['type']) && $form['type']['#value'] .'_node_form' == $form_id) {
    // Add CC license selection to node form
    $node = $form['#node'];
    if (creativecommons_node_type_is_enabled($node->type)) {
        $form = array_merge($form, creativecommons_node_form($form['#node'], $form_state));
    }
  }

  return $form;
}

/**
 * Append Creative Commons license to an RSS <item> node
 */
function creativecommons_xml($node) {
  if ($node->cc) {
    return array(
      array('key' => 'xmlns:creativeCommons', 'value' => $node->cc->license_uri)
    );
  }
  return;
}
/**
 * Append html and rdf content to node.
 *
 * TODO: this is replaced by hook_blook, which can better display human readable
 * license information, but hook_view() seems like it could be used for embedding
 * more meaningful machine readable RDF information (e.g. associating author, title
 * with content, etc.)
 */
function creativecommons_view($node, $teaser = FALSE, $page = FALSE) {
  // As the function is currently deprecated, the following line neuters it
  return;

  if ($node->cc) {
    // append html
    $output = $node->cc->get_html();

    // append rdf
    if (variable_get('creativecommons_rdf', TRUE))
      $output .= "<!-- ". $node->cc->get_rdf() ." -->";
    if ($output) {
      $node->content['body']['#value'] .= '<p class="creativecommons">'. $output .'</p>';
      if ($teaser)
        $node->content['teaser']['#value'] .= '<p class="creativecommons">'. $output .'</p>';
    }

    return $node;
  }
}

/**
 * Implementation of hook_block().
 */
function creativecommons_block($op='list', $delta=0, $edit = array()) {
  // listing of blocks, such as on the admin/block page
  switch ($op) {
    case 'list':
      $blocks[0] = array(
        'info' => t('Creative Commons Node License'),
        'weight' => 0,
        'enabled' => 1,   // default make it enabled
        'region' => 'content',
        'theme' => 'garland',
      );

      $blocks[1] = array(
        'info' => t('Creative Commons Site License'),
        'weight' => -10,
        'enabled' => 1,   // default make it enabled
        'region' => 'footer',
        'theme' => 'garland',
      );

      return $blocks;


    case 'view':
      switch ($delta) {
        // Node license
        case 0:
          if (!is_numeric(arg(1))) {
            return;
          }

          $nid = (int)arg(1);
          $node = node_load(array('nid' => $nid));

          if ( $node && arg(0) == 'node' && ( $node->cc && $node->cc->is_available()) && ( (arg(2)=='view') || (arg(2)=='') ) ) {
            // get license information
            $output = $node->cc->output();

            if ($output) {
              $block['content'] =  '<p class="creativecommons">'. $output .'</p>';
            }
          }

          return $block;

          // Site license
          case 1:
            if (variable_get('creativecommons_site_license_display', FALSE)) {
              $cc = creativecommons_get_default_license();
              $block['content'] =  $cc->output(variable_get('creativecommons_site_license_additional_text', ''));
              return $block;
            }
      }
  }
}

/**
 * Form for attaching Creative Commons license to a node (not a hook)
 */
function creativecommons_node_form($node, $form_state) {
  //TODO: review metadata

  // if no licenses available (in admin > settings > creative commons) then no form displayed
  if (!$selected_licenses = creativecommons_get_available_license_types()) {
    return array();
  }

  // Add validate and submit functions
  $form['#validate'][] = 'creativecommons_node_form_validate';
  $form['#submit'][] = 'creativecommons_node_form_submit';


  $cc_img = '<img src="'. CC_IMG_PATH .'/cc-choose-license.gif" alt="Creative Commons license" />';
  $cc_txt = '<p><a href="http://creativecommons.org/learn/licenses/" target="_blank">Creative Commons licenses</a> help you share your work while keeping your copyright. Other people can copy and distribute your work provided they give you credit -- and only on the conditions you specify here. This form helps you choose those conditions. Visit the Creative Commons website for an <a href="http://creativecommons.org/about/licenses/meet-the-licenses">explanation of the different licenses</a>.

Choose the <a href="http://creativecommons.org/licenses/publicdomain/">Public Domain license</a> or <a href="http://creativecommons.org/publicdomain/zero/1.0/">CC0</a> if you want to offer your work with no conditions.</p>';

  // add javascript to <head>
  $header = "\n  <script type=\"text/javascript\" src=\"". CC_JS_PATH ."/cc_toggle.js\"></script>";
  drupal_set_html_head($header);

  // built html output
  $output = t($cc_txt);

  //$selected = $node->cc_license;
  $selected = (is_null($node->cc_license)) ? $node->cc->license_type  : $node->cc_license;
  $output1 = creativecommons_select_license_form($node, 'cc_license_uri', $form_state['values']['creativecommons']['select_license_form']);


  // if no license, then don't process the metadata
  //  note: this loses the metadata, need to preserve it somehow... maybe load the hidden layer,
  //  without the link to display:block, and no error handling.
  //TODO: review
  if (is_null($selected) || $selected == 'none') {
    $form['creativecommons'] = array(
      '#type' => 'fieldset',
      '#title' => $cc_img,
      '#prefix' => '<div class="attachments">',
      '#suffix' => '</div>',
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#tree' => TRUE,
    );
    $form['creativecommons'][] = array('#value' => $output);
    $form['creativecommons']['select_license_form'] = $output1['select_license_form'];

    return $form;
  }


/// ///////////////////////////////////
//if (!is_null($node->cc_license->license_type) && $node->cc_license->license_type != 'none')
//  $output .= cc_para("not an empty license");
/// //////////////////////////////////////


// required metadata
  $required = variable_get('creativecommons_required', array());

  // loop thru metadata fields
  $fields = '';
  $metadata_types = creativecommons_get_metadata_types();

  $form['creativecommons'] = array(
    '#type' => 'fieldset',
    '#title' => $cc_img,
    '#prefix' => '<div class="attachments">',
    '#suffix' => '</div>',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
  );
  $form['creativecommons'][] = array('#value' => $output);
  $form['creativecommons']['select_license_form'] = $output1['select_license_form'];

  global $user;
  $link_txt = 'Click to include more information about your work.';
  $show_style = ($node->cc->show_meta) ? 'block' : 'none';
  $form['creativecommons'][] = array('#value' => '<p><a onclick="cc_toggle(\'\',\'cc_optional\');return FALSE;" href="javascript:cc_toggle(\'\',\'cc_optional\');return FALSE;"><span id="moreinfo">'. $link_txt .'</span></a></p>');
  $form['creativecommons'][] = array('#value' => '<div id="cc_optional" style="display:'. $show_style .';">');

  $form['creativecommons'][] = array('#value' => cc_para("button to save default user values"));


  foreach ($metadata_types as $m => $d) {
    $sel = ($node->cc->metadata[$m]) ? $node->cc->metadata[$m] : '';

    // validate data
    //if ($required) {
      $req = $required[$m] && $required[$m] != 0 ? TRUE : FALSE;
      if ($req && !$sel && !$node->cc->new) {
        form_set_error("creativecommons][cc][metadata][$m", t("Creative Commons: Please submit the $m for your content."));
        // show metadata block if errors exist
        $node->cc->show_meta = TRUE;
      }
      // show metadata block on creation of post
      else if ($node->cc->new)
        $node->cc->show_meta = TRUE;
    //}

    // build metadata form fields
    switch (drupal_strtolower($m)) {
      case 'format':
        $formats = creativecommons_get_formats();
        // $fields .= form_select(t($d), "cc][metadata][$m", $sel, $formats, NULL, NULL, NULL, $req);
        $form["creativecommons"]["cc"]["metadata"]["$m"] = array(
          '#type' => 'select',
          '#title' => t($d),
          '#default_value' => $sel,
          '#options' => $formats,
          '#description' => NULL,
          '#extra' => NULL,
          '#multiple' => NULL,
          '#required' => $req,
        );
        break;

      case 'description':
        // $fields .= form_textarea(t($d), "cc][metadata][$m", $sel, 60, 5, NULL, NULL, $req);
        $form["creativecommons"]["cc"]["metadata"]["$m"] = array(
          '#type' => 'textarea',
          '#title' => t($d),
          '#default_value' => $sel,
          '#cols' => 60,
          '#rows' => 5,
          '#description' => NULL,
          '#attributes' => NULL,
          '#required' => $req,
        );
        break;

      default:
        // $fields .= form_textfield(t($d), "cc][metadata][$m", $sel, 50, 255, NULL, NULL, $req);
        $form["creativecommons"]["cc"]["metadata"]["$m"] = array(
          '#type' => 'textfield',
          '#title' => t($d),
          '#default_value' => $sel,
          '#size' => 50,
          '#maxlength' => 255,
          '#description' => NULL,
          '#attributes' => NULL,
          '#required' => $req,
        );
        break;
    }
  }

    $form['creativecommons'][] = array('#value' => '</div>');

  return $form;
}



/**
  * Validate the Creative Commons node form.
  */
function creativecommons_node_form_validate($form, &$form_state) {
  /**
   * The case of a non-available license is actually handled well by Drupal already.
   * Drupal says, "an illegal choice has been detected," because only available
   * licenses appear in the form.
   *
   * However, it seems that if a license becomes unavailable after a form is
   * already in edit, or at least the preview stage, then the following check is
   * needed.
   */
  creativecommons_validate_license_uri('cc_license_uri', $form_state['values']['creativecommons']['select_license_form']['cc_license_uri']);

/*  $license_uri = $form_state['values']['creativecommons']['select_license_form']['cc_license_uri'];
  $cc = new creativecommons_license($license_uri);
  if (!$cc->is_available()) {
    form_set_error('creativecommons', $cc->get_full_license_name() .' is no longer available');
  }*/

  // This would be require to check license using questions
  /* $questions = creativecommons_get_questions_array($node->cc_license);
  // loop thru ?s, set to current val, else default to first answer in array
  foreach ($questions as $k => $v) {
    if (in_array($node->cc[$k], $v['answers']))
      $questions[$k]['selected'] = $node->cc[$k];
    else
      $questions[$k]['selected'] = current($v['answers']);
  }*/
}

/**
 * Submit the Creative Commons node form.
 */
function creativecommons_node_form_submit($form, &$form_state) {
//TODO: what is this needed for?
return;

  //Same as creativecommons_save
    if (is_array($_POST['creativecommons']['select_license_form']) ) {
      foreach ($_POST['creativecommons']['select_license_form'] as $key => $val ) {
        $_POST[$key] = $val;
      }
    }

    if (is_array($_POST['creativecommons']['cc']) ) {
      foreach ($_POST['creativecommons']['cc'] as $key => $val ) {
        $_POST['cc'][$key] = $val;
      }
    }

    $cc = new creativecommons_license($_POST['cc_license_uri']);

    //TODO: hook_validate() for this check
    if ($cc && $cc->is_available())
      $node->cc = $cc;



    //TODO: make questions optional
    /* $p = $_POST['cc_license'];
    $questions = creativecommons_get_questions_array($p);
    foreach ($questions as $k => $v) {
      $post_val = $_POST['edit']['cc'][$k];
      if (in_array($post_val, $v['answers'])) {
        $questions[$k]['selected'] = $post_val;
      }
      else {
        // default to first answer in array
        $questions[$k]['selected'] = current($v['answers']);
      }
    }

    if (!$_POST['edit']['cc']['metadata']['source'])
      $_POST['edit']['cc']['metadata']['source'] = $base_url;
    $cc = new creativecommons_license($p, $questions, $_POST['edit']['cc']['metadata']);
    $node->cc = $cc;
    */

}

/**
 * Save license/node relationship in database
 */
function creativecommons_save($node) {

  $cc = new creativecommons_license($_POST['creativecommons']['select_license_form']['cc_license_uri']);
  $cc->save($node->nid);

  //TODO: is this line necessary?
  $node->cc = $cc;

  return;
}

/**
  * Delete node/license relationship from database
  */
function creativecommons_delete($node) {
  if ($node->nid) {
    db_query("DELETE FROM {creativecommons} WHERE nid = %d", $node->nid);
  }
  return;
}


/**
  * Load the license for a specified node. If no license found, return empty
  * license object.
  */
function creativecommons_load($node) {

  if ($node->nid && !isset($node->cc)) {
    $result = db_query("SELECT cc.license_uri FROM {creativecommons} cc WHERE cc.nid = %d", $node->nid);
    if ($row = db_fetch_object($result)) {
      $license_uri = stripslashes($row->license_uri);
    }
  }

  $cc = new creativecommons_license($license_uri);
  return $cc;
}


/**
 * Returns true if Creative Commons licensing is enabled for this node type;
 * false otherwise
 */
function creativecommons_node_type_is_enabled($type) {
  return variable_get('creativecommons_type_'. $type, 0);
}
/**
  *  Debug code
  */
if (function_exists('echo_pre')) {
}
else {

function echo_pre($arr, $head = '') {
  echo "<pre>";
  if ($head !='') {
    echo "$head<br/>";
  }
  print_r($arr);
  echo "</pre>";
}

}
